---
abstract: 'Marpa-based parser for Graph::Easy'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-Easy-Marpa
provides:
  Graph::Easy::Marpa:
    file: lib/Graph/Easy/Marpa.pm
    version: 1.07
  Graph::Easy::Marpa::Lexer:
    file: lib/Graph/Easy/Marpa/Lexer.pm
    version: 1.07
  Graph::Easy::Marpa::Lexer::DFA:
    file: lib/Graph/Easy/Marpa/Lexer/DFA.pm
    version: 1.07
  Graph::Easy::Marpa::Parser:
    file: lib/Graph/Easy/Marpa/Parser.pm
    version: 1.07
  Graph::Easy::Marpa::Renderer::GraphViz2:
    file: lib/Graph/Easy/Marpa/Renderer/GraphViz2.pm
    version: 1.07
  Graph::Easy::Marpa::Utils:
    file: lib/Graph/Easy/Marpa/Utils.pm
    version: 1.07
requires:
  Capture::Tiny: 0.11
  Data::Section::Simple: 0.02
  Date::Format: 2.24
  File::Basename: 2.78
  File::Remove: 1.49
  File::Slurp: 9999.19
  File::Spec: 3.33
  File::Temp: 0.22
  Getopt::Long: 2.38
  GraphViz2: 1.09
  Hash::FieldHash: 0.1
  IO::File: 1.14
  List::Compare: 0.37
  List::Cycle: 1
  Log::Handler: 0.71
  Marpa::XS: 0.026
  Module::Load: 0.18
  Perl6::Slurp: 0.03
  Pod::Usage: 1.36
  Set::Array: 0.23
  Set::FA::Element: 1.08
  Sort::Naturally: 1.02
  Text::CSV_XS: 0.8
  Text::Xslate: 1.4001
  Try::Tiny: 0.09
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.07
