---
abstract: 'Marpa-based parser for Graph::Easy'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-Easy-Marpa
provides:
  Graph::Easy::Marpa:
    file: lib/Graph/Easy/Marpa.pm
    version: 0.90
  Graph::Easy::Marpa::Lexer:
    file: lib/Graph/Easy/Marpa/Lexer.pm
    version: 0.90
  Graph::Easy::Marpa::Lexer::DFA:
    file: lib/Graph/Easy/Marpa/Lexer/DFA.pm
    version: 0.90
  Graph::Easy::Marpa::Parser:
    file: lib/Graph/Easy/Marpa/Parser.pm
    version: 0.90
  Graph::Easy::Marpa::Renderer::GraphViz2:
    file: lib/Graph/Easy/Marpa/Renderer/GraphViz2.pm
    version: 0.90
  Graph::Easy::Marpa::Utils:
    file: lib/Graph/Easy/Marpa/Utils.pm
    version: 0.90
requires:
  Hash::FieldHash: 0.1
  IO::File: 1.14
  List::Compare: 0.37
  Log::Handler: 0.71
  Marpa: 0.202
  OpenOffice::OODoc: 2.125
  Perl6::Slurp: 0.03
  Set::Array: 0.23
  Set::FA: 1.04
  Text::CSV_XS: 0.8
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.90
